language: node_js
node_js:
  - node
sudo: false
cache: yarn
before_install:
  - yarn install
  - yarn build
script:
  - yarn test:coverage
after_success:
  - yarn add --dev coveralls
  - cat ./coverage/lcov.info | coveralls

